trigger:
- main  # Change this to your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting Build and Deploy'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  #  Docker registry name
    repository: 'riyarepo'  # Docker repository name
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  #  Docker registry name
    repository: 'riyarepo'  #Docker repository name
    command: 'push'
    tags: '$(Build.BuildId)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ' Free Tier '  # zure service connection name
    appType: 'webAppContainer'
    WebAppName: 'webapp-weather'  # Azure App Service name
    DockerNamespace: 'weathermanriya'
    DockerRepository: 'riyarepo'
    DockerImageTag: '$(Build.BuildId)'