trigger:
- main  # Change this to your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting Build and Deploy'

- task: UseNode@2
  inputs:
    version: '14'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  # Replace with your Docker registry name
    repository: 'riyarepo'  # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '$(Build.BuildId)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'YourAzureServiceConnection'  # Replace with your Azure service connection name
    appType: 'webAppContainer'
    WebAppName: 'YourWebAppName'  # Replace with your Azure App Service name
    DockerNamespace: 'weathermanriya'
    DockerRepository: 'riyarepo'
    DockerImageTag: '$(Build.BuildId)'