trigger:
- main  # Change this to your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting Build and Deploy'

- task: UseNode@2
  inputs:
    version: '14'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'
    repository: 'riyarepo'  #Docker repository name
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  #  Docker registry name
    repository: 'riyarepo'  # Docker repository name
    command: 'push'
    tags: '$(Build.BuildId)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial'  #Azure service connection name
    appType: 'webAppContainer'
    WebAppName: 'webapp-weather'  #Azure App Service name
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: false
    DockerNamespace: 'weathermanriya'
    DockerRepository: 'riyarepo'
    DockerImageTag: '$(Build.BuildId)'
