trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting Build and Deploy'

- task: UseNode@2
  inputs:
    version: '14'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  #  Docker registry name
    repository: 'riyarepo'  # your Docker repository name
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@2
  inputs:
    containerRegistry: 'weathermanriya'  # Docker registry name
    repository: 'riyarepo'  # Docker repository name
    command: 'push'
    tags: '$(Build.BuildId)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Tier'  # Replace with your Azure service connection name
    appType: 'webAppContainer'
    WebAppName: 'webapp-weather'  # Replace with your Azure App Service name
    DockerNamespace: 'weathermanriya'
    DockerRepository: 'riyarepo'
    DockerImageTag: '$(Build.BuildId)'